"""Initial schema

Revision ID: ad7a7e6f39fb
Revises: 
Create Date: 2026-09-17 22:38:59.338673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'ad7a7e6f39fb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('total_area', sa.Float(), nullable=True),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('ecosystem_type', sa.String(), nullable=True),
    sa.Column('monitoring_status', sa.String(), nullable=True),
    sa.Column('carbon_baseline', sa.Float(), nullable=True),
    sa.Column('current_carbon_estimate', sa.Float(), nullable=True),
    sa.Column('biodiversity_index', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_index(op.f('ix_sites_monitoring_status'), 'sites', ['monitoring_status'], unique=False)
    op.create_index(op.f('ix_sites_project_id'), 'sites', ['project_id'], unique=False)
    op.create_table('biodiversity_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.Date(), nullable=False),
    sa.Column('index_score', sa.Float(), nullable=False),
    sa.Column('species_count', sa.Integer(), nullable=True),
    sa.Column('habitat_health', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biodiversity_metrics_recorded_at'), 'biodiversity_metrics', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_biodiversity_metrics_site_id'), 'biodiversity_metrics', ['site_id'], unique=False)
    op.create_table('carbon_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.Date(), nullable=False),
    sa.Column('co2e_tonnes', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carbon_metrics_recorded_at'), 'carbon_metrics', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_carbon_metrics_site_id'), 'carbon_metrics', ['site_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_carbon_metrics_site_id'), table_name='carbon_metrics')
    op.drop_index(op.f('ix_carbon_metrics_recorded_at'), table_name='carbon_metrics')
    op.drop_table('carbon_metrics')
    op.drop_index(op.f('ix_biodiversity_metrics_site_id'), table_name='biodiversity_metrics')
    op.drop_index(op.f('ix_biodiversity_metrics_recorded_at'), table_name='biodiversity_metrics')
    op.drop_table('biodiversity_metrics')
    op.drop_index(op.f('ix_sites_project_id'), table_name='sites')
    op.drop_index(op.f('ix_sites_monitoring_status'), table_name='sites')

    op.drop_table('sites')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
